baseURL: ""
languageCode: en-us
title: Human Pangenome
theme: PaperMod

params:
  homeInfoParams:
    Title: "Hello"
    Content: "Welcome to the Human Pangenome Page!"
  ShowShareButtons: true

menu:
  main:
    - identifier: aboutus
      name: About Us
      url: /aboutus/
      weight: 10
    - identifier: data
      name: Data and Resources
      url: /data/
      weight: 20
    - identifier: events
      name: Events and Presentations
      url: /events/
      weight: 30
    - identifier: publications
      name: Publications
      url: /publications/
      weight: 40
    - identifier: contact
      name: Contact Us
      url: /contact/
      weight: 50