baseURL: ""
languageCode: en-us
title: Human Pangenome
theme: "PaperMod"

params:
  homeInfoParams:
    Title: "Hello"
    Content: "Welcome to the Human Pangenome Page!"
  ShowShareButtons: true
  mainSections: true
  socialIcons:
    - name: twitter
      url: "https://twitter.com/HumanPangenome"
    - name: wikipedia
      url: "http://wiki.humanpangenome.org/"
    - name: github
      url: "https://github.com/"
  label:
    text: "Human Pangenome"
    icon: /img/Logo.png
    iconHeight: 40

menu:
  main:
    - identifier: aboutus
      name: About Us
      url: /aboutus/
      weight: 10
    - identifier: data
      name: Data & Resources
      url: /data/
      weight: 20
    - identifier: events
      name: Events & Presentations
      url: /events/
      weight: 30
    - identifier: publications
      name: Publications
      url: /publications/
      weight: 40
    - identifier: contact
      name: Contact Us
      url: /contact/
      weight: 50